In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

In [1]:
import pandas as pd
# 文件路径
file_path = "/hongyi/stream/dataset/cnews.test.txt"
# 创建一个空列表来存储处理后的数据
data = []
# 打开文件并读取每一行
with open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        # 确保每一行至少有4个字符
        if len(line) > 3:
            # 提取前两个字符作为第一个元素
            first_two_chars = line[:2].strip()
            # 提取从第四个字开始的剩余部分作为第二个元素
            remaining_chars = line[3:].strip()
            # 将两个元素添加到列表中
            data.append([remaining_chars, first_two_chars])

# 创建 DataFrame
df = pd.DataFrame(data, columns=["text", "labels"])
# 显示 DataFrame
print(df)

                                                   text labels
0     鲍勃库西奖归谁属？ NCAA最强控卫是坎巴还是弗神新浪体育讯如今，本赛季的NCAA进入到了末...     体育
1     麦基砍28+18+5却充满寂寞 纪录之夜他的痛阿联最懂新浪体育讯上天对每个人都是公平的，贾维...     体育
2     黄蜂vs湖人首发：科比冲击七连胜 火箭两旧将登场新浪体育讯北京时间3月28日，NBA常规赛洛...     体育
3     双面谢亚龙作秀终成做作 谁来为低劣行政能力埋单是谁任命了谢亚龙？谁放纵了谢亚龙？谁又该为谢亚...     体育
4     兔年首战山西换帅后有虎胆 张学文用乔丹名言励志今晚客场挑战浙江稠州银行队，是山西汾酒男篮的兔...     体育
...                                                 ...    ...
9995  近期18只偏股基金成立 将为股市新增300亿资金兴业有机增长混合基金23日发布公告称，基金募...     财经
9996  银华基金杨靖聊政策性主题投资机会实录新浪财经讯 银华和谐主题基金拟任基金经理助理杨靖于3月2...     财经
9997  首只基金投资信心指数问世本报讯 (记者吴敏)昨日，嘉实基金宣布推出“嘉实中国基金投资者信心指...     财经
9998  17只阳光私募3月份火速成立证券时报记者 方 丽本报讯 阳光私募产品迎来了发行高潮。WIND...     财经
9999  25日股票基金全线受挫 九成半基金跌逾1%全景网3月26日讯 周三开放式基金净值普降，股票型...     财经

[10000 rows x 2 columns]


In [2]:
#本段落用时9min
from stream_topic.utils.dataset import TMDataset

# 创建 TMDataset 实例
dataset = TMDataset(language="zh-cn", stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt')
# 假设你有一个名为 df 的 DataFrame，包含你的数据
# df = pd.DataFrame(...)

# 数据集名称
dataset_name = "my_dataset"
# df = df.iloc[0:100]
# 指定保存数据集的目录
save_dir = "/hongyi/stream/dataset"
# df = df.iloc[0:1000]
# 调用 create_load_save_dataset 方法来存储数据集
dataset.create_load_save_dataset(
    data=df,
    dataset_name=dataset_name,
    save_dir=save_dir,
    doc_column="text",  # 假设 DataFrame 中包含文本的列名为 "text_column"
    label_column="labels",  # 假设 DataFrame 中包含标签的列名为 "label_column"
    language = "zh-cn",
    stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt'
)
# 打印保存的数据集信息
print(dataset.dataframe.head())

/hongyi/anaconda3/envs/mystream/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
Preprocessing documents:   0%|                                                               | 0/10000 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.567 seconds.
Prefix dict has been built successfully.
Preprocessing documents: 100%|██████████████████████████████████████████████████| 10000/10000 [01:27<00:00, 113.75it/s]
2024-11-11 14:39:58.331 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:239 - Dataset saved to /hongyi/stream/dataset/my_dataset.parquet
2024-11-11 14:39:58.372 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:254 - Dataset info saved to /hongyi/stre

  language                              stopwords_path  \
0    zh-cn  /hongyi/stream/stopwords/scu_stopwords.txt   
1    zh-cn  /hongyi/stream/stopwords/scu_stopwords.txt   
2    zh-cn  /hongyi/stream/stopwords/scu_stopwords.txt   
3    zh-cn  /hongyi/stream/stopwords/scu_stopwords.txt   
4    zh-cn  /hongyi/stream/stopwords/scu_stopwords.txt   

                                                text labels  
0  本赛季 史密斯 吉梅尔 杨百翰 吉梅尔 领导者 杨百翰 主教练 主教练 史密斯 杜克大学 史...     体育  
1            体育讯 上半场 上半场 上半场 惠特曼 惠特曼 本赛季 下半场 上半场 下半场     体育  
2                                        体育讯 直播室 直播室     体育  
3  谢亚龙 谢亚龙 谢亚龙 谢亚龙 南勇们 谢亚龙 掌门人 谢亚龙 立案侦查 蔚少辉 李冬生 谢...     体育  
4  张学文 山西汾酒 山西队 浙江队 山西汾酒 山西队 浙江队 山西队 山西队 浙江队 山西队 ...     体育  


In [3]:
from stream_topic.models import KmeansTM
from stream_topic.utils import TMDataset

#本段落用时9min
dataset = TMDataset(language="zh-cn",stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt')# 
dataset.fetch_dataset(name = "my_dataset", dataset_path = "/hongyi/stream/dataset", source = 'local')
dataset.preprocess(model_type="KmeansTM", min_word_length = 1)
#本段落用时4h
model = KmeansTM('/hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/',stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt')# 
model.fit(dataset, n_topics=10)

topics = model.get_topics()
print(topics)

2024-11-11 14:46:33.810 | INFO     | stream_topic.utils.dataset:fetch_dataset:120 - Fetching dataset: my_dataset
2024-11-11 14:46:33.811 | INFO     | stream_topic.utils.dataset:fetch_dataset:130 - Fetching dataset from local path
Preprocessing documents: 100%|█████████████████████████████████████████████████| 10000/10000 [00:08<00:00, 1138.56it/s]
2024-11-11 14:46:49.969 | INFO     | stream_topic.models.KmeansTM:fit:212 - --- Training KmeansTM topic model ---
2024-11-11 14:46:50.995 | INFO     | stream_topic.models.abstract_helper_models.base:prepare_embeddings:225 - --- Creating /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/ document embeddings ---
100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [02:52<00:00, 57.99it/s]
2024-11-11 14:49:45.362 | INFO     | stream_topic.models.abstract_helper_models.base:dim_reduction:196 - --- Reducing dimensions ---
2024-11-11 14:50:22.629 | INFO     | stream_topic.models.Kme

[['电影节', '好莱坞', '预告片', '范冰冰', '张柏芝', '章子怡', '李连杰', '女主角', '五月天', '发布会'], ['数码相机', '传感器', '分辨率', '感应器', '显示屏', '液晶屏', '参考价格', '感光度', '变焦镜头', '处理器'], ['型基金', '投资者', '收益率', '今年以来', '封闭式', '基金净值', '易方达', '增长率', '货币基金', '混合型'], ['季后赛', '体育讯', '詹姆斯', '本赛季', '湖人队', '凯尔特人', '常规赛', '尼克斯', '加索尔', '安东尼'], ['留学生', '加拿大', '四六级', '毕业生', '申请人', '澳大利亚', '奖学金', '研究生', '新西兰', '新加坡'], ['连衣裙', '高跟鞋', '牛仔裤', '设计师', '针织衫', '比基尼', '女人味', '蝴蝶结', '羽绒服', '太阳镜'], ['房地产', '消费者', '开发商', '平方米', '二手房', '成交量', '万平方米', '木地板', '商品房', '购房者'], ['龚松林', '大酒店', '大错特错', '大门口', '大闹天宫', '大队人马', '大陆行', '大院里', '大雁塔', '大雅之堂'], ['手机游戏', '网络游戏', '官方网站', '女儿国', '掌上明珠', '让玩家', '客户端', '服务器', '充值卡', '资料片'], ['马英九', '陈水扁', '胡锦涛', '领导人', '国务院', '进一步', '金融危机', '温家宝', '俄罗斯', '中新网']]


In [4]:
from stream_topic.metrics import ISIM, INT, ISH,Expressivity, NPMI, Embedding_Coherence, Embedding_Topic_Diversity
from sentence_transformers import SentenceTransformer
from stream_topic.metrics.metrics_config import MetricsConfig
MetricsConfig.set_PARAPHRASE_embedder("/hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/")#paraphrase-multilingual-mpnet-base-v2
MetricsConfig.set_SENTENCE_embedder("/hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/")#all-mpnet-base-v2

In [10]:
import numpy as np
score_list=[]
metric = ISIM()
for i in range(500):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISIM scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
ISIM scores: 0.4583348022460938


In [9]:
score_list=[]
metric = INT()
for i in range(500):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("INT scores:", scores)

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
INT scores: 0.24


In [11]:
score_list=[]
metric = ISH()
for i in range(500):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISH scores:", scores)

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
ISH scores: 0.6054579943418503


In [12]:
import pandas as pd
def load_stopwords(stopwords_path):
        # load Chinese stopwords list
        return pd.read_csv(stopwords_path, names=['w'], sep='\t', encoding='UTF-8')

In [13]:
stopword = load_stopwords('/hongyi/stream/stopwords/scu_stopwords.txt')
expressivity_metric = Expressivity(
n_words=5,
custom_stopwords=list(stopword)
)
beta = np.random.rand(10, 384) #主题数，嵌入维度
info = expressivity_metric.get_info()
print("Metric Info:", info)
scores = expressivity_metric.score(topics, beta)  #值越小越好
print("Expressivity scores:", scores)

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Metric Info: {'metric_name': 'Expressivity', 'n_words': 5, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: XLMRobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The expressivity metric measures the distance between the mean vector of the top words in a topic and the m

In [14]:
beta = np.random.rand(10, 384)
diversity_metric = Embedding_Topic_Diversity()
info = diversity_metric.get_info()
print("Metric Info:", info)
scores = diversity_metric.score(topics, beta)  #值越小越好
print("Diversity score:", scores)

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Metric Info: {'metric_name': 'Embedding Topic Diversity', 'n_words': 10, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: XLMRobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The diversity metric measures the mean cosine similarity of the mean vectors of the top words of all topics.'}
Diversity score: 0.7194263865279577


In [15]:
metric = NPMI(dataset,language = "chinese") #值越大越好
metric.score(topics)

-0.95939

In [16]:
metric = Embedding_Coherence()
topic_scores = metric.score_per_topic(topics)
print("Coherence scores per topic:", topic_scores)
overall_score = metric.score(topics)
print("Overall coherence score:", overall_score)

Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
1
Loading model from local path: /hongyi/stream/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/
Coherence scores per topic: {'电影节, 好莱坞, 预告片, 范冰冰, 张柏芝': 0.66974, '数码相机, 传感器, 分辨率, 感应器, 显示屏': 0.56482, '型基金, 投资者, 收益率, 今年以来, 封闭式': 0.45252, '季后赛, 体育讯, 詹姆斯, 本赛季, 湖人队': 0.66196, '留学生, 加拿大, 四六级, 毕业生, 申请人': 0.48822, '连衣裙, 高跟鞋, 牛仔裤, 设计师, 针织衫': 0.58639, '房地产, 消费者, 开发商, 平方米, 二手房': 0.59031, '龚松林, 大酒店, 大错特错, 大门口, 大闹天宫': 0.59984, '手机游戏, 网络游戏, 官方网站, 女儿国, 掌上明珠': 0.5203, '马英九, 陈水扁, 胡锦涛, 领导人, 国务院': 0.5527}
Overall coherence score: 0.56868


In [17]:
metric.score_per_topic(topics)

{'电影节, 好莱坞, 预告片, 范冰冰, 张柏芝': 0.66974,
 '数码相机, 传感器, 分辨率, 感应器, 显示屏': 0.56482,
 '型基金, 投资者, 收益率, 今年以来, 封闭式': 0.45252,
 '季后赛, 体育讯, 詹姆斯, 本赛季, 湖人队': 0.66196,
 '留学生, 加拿大, 四六级, 毕业生, 申请人': 0.48822,
 '连衣裙, 高跟鞋, 牛仔裤, 设计师, 针织衫': 0.58639,
 '房地产, 消费者, 开发商, 平方米, 二手房': 0.59031,
 '龚松林, 大酒店, 大错特错, 大门口, 大闹天宫': 0.59984,
 '手机游戏, 网络游戏, 官方网站, 女儿国, 掌上明珠': 0.5203,
 '马英九, 陈水扁, 胡锦涛, 领导人, 国务院': 0.5527}

In [18]:
from octis.evaluation_metrics.diversity_metrics import TopicDiversity

model_output = {"topics": model.get_topics(), "topic-word-matrix": model.get_beta(), "topic-document-matrix": model.get_theta()}

metric = TopicDiversity(topk=10) # Initialize metric
topic_diversity_score = metric.score(model_output)
print(topic_diversity_score)

1.0


In [19]:
from sklearn.metrics import confusion_matrix
label_mapping = {
    '体育': 7,
    '娱乐': 9,
    '家居': 5,
    '房产': 4,
    '教育': 0,
    '时尚': 6,
    '时政': 2,
    '游戏': 3,
    '科技': 8,
    '财经': 1
} #随便设置

predictions = model.predict(dataset.texts)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [02:47<00:00, 59.76it/s]


In [20]:
# 假设 dataset.labels 包含所有样本的真实标签
true_labels = dataset.labels

# 将汉字类别转换为数值类别
true_labels_numeric = [label_mapping[label] for label in true_labels]

# 将预测结果和真实标签转换为 DataFrame
df_predictions = pd.DataFrame(predictions, columns=['predicted_labels'])
df_true_labels = pd.DataFrame(true_labels_numeric, columns=['true_labels'])

# 计算混淆矩阵
conf_matrix = confusion_matrix(df_true_labels, df_predictions)
# 如果你想要更详细的信息，可以打印整个混淆矩阵
print('Confusion Matrix:')
print(conf_matrix)

Confusion Matrix:
[[ 35   2   7   7 803  26  51   0   6  63]
 [  5   0 794   0   1   3  25   0   3 169]
 [ 15   0  11   1  40   2  43   0   5 883]
 [ 67   2   1  16   7  86  22   1 779  19]
 [  6   0  26   1   6  16 810   2   1 132]
 [ 33   3   4  12  11  61 790  11   5  70]
 [101   1   0   8   7 815  24  17  15  12]
 [  7   0   0 970   2   1   1   0   1  18]
 [  9 914   0   2   1  12  34   3  10  15]
 [922   0   0   5   2  20   4   1  11  35]]
