In [1]:
topics = [['比赛', '体育讯', '球队', '防守', '季后赛', '球员', '进攻', '篮板', '热火', '湖人'],['比赛', '球队', '热火', '球员', '季后赛', '防守', '湖人', '篮板', '科比', '凯尔特人']]

In [9]:
import pandas as pd

# 读取文件并加载为 DataFrame
df = pd.read_csv('/hongyi/stream/dataset/paper_data/THUCNews_small.txt', sep='\t', header=None, names=['text','labels'])

# 查看结果
print(df.head())


                                                text labels
0  胜负彩11066期部分专业媒体复式推荐总汇   说明：媒体推荐的“历史命中率统计”表示媒体历...     彩票
1  胜负彩11097期部分专业媒体复式推荐总汇 说明：媒体推荐的“历史命中率统计”表示媒体历史平...     彩票
2  胜负彩第09069期国内部分专业媒体复式推荐总汇表 说明：媒体推荐的“历史命中率统计”表示媒...     彩票
3  单期361注2等奖改写历史 全偶号让双色球头奖走低 　　双色球第09083期头奖爆出11注5...     彩票
4  双色球头奖14注597万 二等124注16万奖池1.33亿 　　新浪体育讯　北京时间2011...     彩票


In [3]:
import numpy as np
np.unique(df['labels'])

array(['agriculture', 'car', 'culture', 'edu', 'entertainment', 'finance',
       'game', 'house', 'military', 'sports', 'story', 'tech', 'travel',
       'world'], dtype=object)

In [10]:
df['labels'].value_counts()

labels
彩票    700
游戏    700
财经    700
教育    700
房产    700
娱乐    700
科技    700
时尚    700
时政    700
家居    700
体育    700
股票    700
社会    700
星座    700
Name: count, dtype: int64

In [11]:
import re
file_path = "/hongyi/stream/dataset/paper_data/THUCNews_small.txt"
df = pd.read_csv(file_path, sep='\t', header=None, names=['text', 'labels'], encoding='utf-8')

# 正则表达式：匹配中文字符
chinese_pattern = re.compile(r'[\u4e00-\u9fa5]')

# 将非字符串值（例如 NaN 或 None）转换为字符串或空字符串
df['text'] = df['text'].fillna('').astype(str)

# 找到包含中文字符的行
contains_chinese = df['text'].apply(lambda x: bool(chinese_pattern.search(x)))

# 输出包含中文字符的行
df_with_chinese = df[-contains_chinese]
print("包含中文字符的行：")
print(df_with_chinese)

# 删除不包含中文字符的行
df_without_chinese = df[contains_chinese]

# 保存删除不包含中文字符的行后的 DataFrame
df_without_chinese.to_csv("/hongyi/stream/dataset/paper_data/THUCNews_small_cleaned.txt", sep='\t', index=False, header=False, encoding='utf-8')

包含中文字符的行：
Empty DataFrame
Columns: [text, labels]
Index: []


In [20]:
# 读取第一个文件 
with open('/hongyi/stream/dataset/paper_data/train_fudan_cleaned.txt',  'r', encoding='utf-8') as file1:
    content1 = file1.read() 
 
# 读取第二个文件 
with open('/hongyi/stream/dataset/paper_data/test_fudan_cleaned.txt',  'r', encoding='utf-8') as file2:
    content2 = file2.read() 
 
# 合并内容 
combined_content = content1 + content2 
 
# 写入新文件 
with open('/hongyi/stream/dataset/paper_data/fudan_cleaned.txt',  'w', encoding='utf-8') as combined_file:
    combined_file.write(combined_content) 
 
print("文件已成功合并为 combined_file.txt") 

文件已成功合并为 combined_file.txt


In [17]:
def read_stopwords(filename):
    """读取停用词表文件"""
    with open(filename, 'r', encoding='utf-8') as f:
        return set(line.strip()  for line in f if line.strip()) 
import itertools 

# 定义四个停用词表文件路径 
files = [
    '/hongyi/stream/stopwords/baidu_stopwords.txt', 
    '/hongyi/stream/stopwords/fdu_stopwords.txt', 
    '/hongyi/stream/stopwords/scu_stopwords.txt', 
    '/hongyi/stream/stopwords/hit_stopwords.txt' ,
    '/hongyi/stream/stopwords/cn_stopwords.txt'
]

# 读取所有停用词表为集合 
sets = []
for file in files:
    sets.append(read_stopwords(file)) 

# 计算所有两两组合的交集 
common_words = set()
for a, b in itertools.combinations(sets,  2):
    intersection = a & b  # 计算交集 
    common_words.update(intersection) 

# 计算所有出现过的词语 
all_words = set()
for s in sets:
    all_words.update(s) 

# 找出只在一个来源中出现的词语 
singular_words = all_words - common_words 

# 将结果保存到新文件 
with open('/hongyi/stream/stopwords/common_stopwords.txt',  'w', encoding='utf-8') as f:
    for word in sorted(common_words):
        f.write(word  + '\n')  # 确保每行只有一个单词 

with open('/hongyi/stream/stopwords/singular_stopwords.txt',  'w', encoding='utf-8') as f:
    for word in sorted(singular_words):
        f.write(word  + '\n')

In [10]:
import pandas as pd
# 文件路径
file_path = "/hongyi/stream/dataset/cnews.val.txt"
# 创建一个空列表来存储处理后的数据
data = []
# 打开文件并读取每一行
with open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        # 确保每一行至少有4个字符
        if len(line) > 3:
            # 提取前两个字符作为第一个元素
            first_two_chars = line[:2].strip()
            # 提取从第四个字开始的剩余部分作为第二个元素
            remaining_chars = line[3:].strip()
            # 将两个元素添加到列表中
            data.append([remaining_chars, first_two_chars])

# 创建 DataFrame
df = pd.DataFrame(data, columns=["text", "labels"])
# 显示 DataFrame
print(df)

                                                   text labels
0     黄蜂vs湖人首发：科比带伤战保罗 加索尔救赎之战 新浪体育讯北京时间4月27日，NBA季后赛...     体育
1     1.7秒神之一击救马刺王朝于危难 这个新秀有点牛！新浪体育讯在刚刚结束的比赛中，回到主场的马...     体育
2     1人灭掘金！神般杜兰特！ 他想要分的时候没人能挡新浪体育讯在NBA的世界里，真的猛男，敢于直...     体育
3     韩国国奥20人名单：朴周永领衔 两世界杯国脚入选新浪体育讯据韩联社首尔9月17日电 韩国国奥...     体育
4     天才中锋崇拜王治郅 周琦：球员最终是靠实力说话2月14日从土耳其男篮邀请赛回到北京之后，周琦...     体育
...                                                 ...    ...
4995  五基金同发分红公告早报讯 (记者孟梅 实习生夏冬梅) 在近期包括本报在内的媒体对部分基金不愿...     财经
4996  今年基金高管变动增多2009年，A股市场一路反弹至2500点上方。虽然股指反弹幅度已经超过3...     财经
4997  偏股基金单季加仓9个百分点整体股票仓位回升至熊市初期水平，“领先”沪指近一千点⊙本报记者 弘...     财经
4998  创投基金被盗第一案原告胜诉获赔4月20日，黑龙江辰能哈工大高科技风险投资有限公司发起设立了黑...     财经
4999  华夏大盘逆势减仓近5%大多数基金一季度加仓□晨报记者 李锐在一片加仓声中，一季度减仓的基金备...     财经

[5000 rows x 2 columns]


In [53]:
import pandas as pd
df = pd.read_csv('/hongyi/stream/dataset/paper_data/CMtMedQA_ten.txt',  sep='\t', encoding='utf-8')
df

,text,labels
0,前列腺炎小出现腹痛多久消失？这样的情况出现好几次，该怎么办呢？\n您好，很高兴为您解答。对于...,男科
1,医生，请问怎样预防前列腺增生伴钙化？我最近发现自己有这种情况，不知道该怎么办呢。\n对于前列...,男科
2,医生，我最近查出来有前列腺增生伴钙化，这是什么情况？会有什么影响吗？\n您好！前列腺增生伴钙...,男科
3,我最近有一些症状，我怀疑我可能患上前列腺增生伴钙化。请问，前列腺增生伴钙化的症状有哪些？\n...,男科
4,医生，我最近听说男性前列腺增生对健康有危害，我想了解一下具体情况。我是36岁的男性。\n您好...,男科
...,...,...
48409,我得了新冠，转阴又复阳了，怎么办？\n了解您的情况，新冠病毒感染后出现转阴又复阳的情况可能是...,内科
48410,我想知道如何避免新冠复阳的传染。\n您好！要避免感染新冠病毒，我们需要保持良好的个人卫生习惯...,内科
48411,感染新冠治好后复阳怎么回事？\n您好！感染新冠病毒后治愈，出现复阳的情况是有可能的。这种情况...,内科
48412,我是新冠患者，最近复阳了，感觉胸闷，这是怎么回事？\n您好，对于新冠患者复阳后出现胸闷的情况...,内科


In [54]:
#本段落用时9min
from stream_topic.utils.dataset import TMDataset

# 创建 TMDataset 实例
dataset = TMDataset()#language="zh-cn", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt'

# 假设你有一个名为 df 的 DataFrame，包含你的数据
# df = pd.DataFrame(...)

# 数据集名称
dataset_name = "CMtMedQA_ten"

# 指定保存数据集的目录
save_dir = "/hongyi/stream/dataset/paper_data"
# df = df.iloc[0:100]
# 调用 create_load_save_dataset 方法来存储数据集
dataset.create_load_save_dataset(
    data=df,
    dataset_name=dataset_name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    save_dir=save_dir,
    doc_column="text",  # 假设 DataFrame 中包含文本的列名为 "text_column"
    label_column="labels",  # 假设 DataFrame 中包含标签的列名为 "label_column"
    language = "chinese",
    stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt',
    min_word_length = 1
)

# 打印保存的数据集信息
print(dataset.dataframe.head())

Preprocessing documents: 100%|██████████████████████████████████████████████████████████████████████████████| 48414/48414 [03:24<00:00, 236.28it/s]
2025-03-14 11:56:36.731 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:238 - Dataset saved to /hongyi/stream/dataset/paper_data/CMtMedQA_ten.parquet
2025-03-14 11:56:36.743 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:255 - Dataset info saved to /hongyi/stream/dataset/paper_data/CMtMedQA_ten_info.pkl


  language                                 stopwords_path  min_word_length  \
0  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1   
1  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1   
2  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1   
3  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1   
4  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1   

                                                text labels  
0  前列腺炎 出现 腹痛 情况 出现 前列腺炎 腹痛 通常 正确 前列腺炎 会 出现 情况 通常...     男科  
1  医生 预防 前列腺 增生 伴 钙化 这种 情况 前列腺 增生 伴 钙化 预防 重要 注意 生...     男科  
2  医生 最近 前列腺 增生 伴 钙化 情况 会 影响 您好 前列腺 增生 伴 钙化 前列腺 增...     男科  
3  最近 症状 前列腺 增生 伴 钙化 请问 前列腺 增生 伴 钙化 症状 您好 前列腺 增生 ...     男科  
4  医生 最近 男性 前列腺 增生 健康 危害 了解 男性 您好 男性 前列腺 增生 三种 明显...     男科  


In [6]:
from stream_topic.models import KmeansTM,BERTopicTM,CBC,DCTE,NMFTM,SOMTM,CEDC,ETM,LDA,ProdLDA,SOMTM,NSTM,WordCluTM,CTM,TNTM,NeuralLDA,CTMNeg
from stream_topic.utils import TMDataset
#本段落用时9min
dataset = TMDataset(language="chinese", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt')# 
# dataset.fetch_dataset(name = "cnews_test", dataset_path = "/hongyi/stream/dataset", source = 'local')
dataset.fetch_dataset(name = "THUCNews_small", dataset_path = "/hongyi/stream/dataset/paper_data", source = 'local')
dataset.preprocess(model_type="CTM", min_word_length = 1)
#本段落用时4h
# model = KmeansTM(embedding_model_name="/hongyi/stream/sentence-transformers/Conan-embedding-v1/",stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt')#
# model.fit(dataset,n_topics=2)
model = CTM(embedding_model_name="/hongyi/stream/sentence-transformers/Conan-embedding-v1/")# 
model.fit(dataset,n_topics=10,max_epochs=5)

topics = model.get_topics()
print(topics)

2025-03-13 19:53:16.216 | INFO     | stream_topic.utils.dataset:fetch_dataset:119 - Fetching dataset: THUCNews_small
2025-03-13 19:53:16.219 | INFO     | stream_topic.utils.dataset:fetch_dataset:129 - Fetching dataset from local path
Preprocessing documents: 100%|██████████████████████████████████████████████████████████████████████████████| 14000/14000 [01:27<00:00, 160.66it/s]
2025-03-13 19:54:44.281 | WARNING  | stream_topic.commons.check_steps:check_dataset_steps:45 - The following preprocessing steps are recommended for the CTM model:
lowercase,
lemmatize,
stem,
expand_contractions,
remove_accents
Include them by running: dataset.preprocess(model_type='CTM')
2025-03-13 19:54:44.982 | INFO     | stream_topic.models.abstract_helper_models.base:prepare_embeddings:225 - --- Creating /hongyi/stream/sentence-transformers/Conan-embedding-v1/ document embeddings ---
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 14000/14000 [

Sanity Checking: |                                                   | 0/? [00:00<?, ?it/s]

/hongyi/anaconda3/envs/mystream/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=255` in the `DataLoader` to improve performance.
/hongyi/anaconda3/envs/mystream/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=255` in the `DataLoader` to improve performance.


Training: |                                                          | 0/? [00:00<?, ?it/s]

Validation: |                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                 …

Validation: |                                                                                                 …

Validation: |                                                                                                 …

`Trainer.fit` stopped: `max_epochs=5` reached.
2025-03-13 20:05:53.151 | INFO     | stream_topic.models.ctm:fit:474 - --- Training completed successfully. ---


[['组图', '床底', '日益突出', '美亚', '保龄', '界龙', '钦笔', '陈航', '加莫则', '回头路'], ['主场', '体育讯', '双色球', '比赛', '不败', '联赛', '开出', '客场', '赛季', '彩民'], ['特别', '很多', '工作', '学生', '考生', '事情', '考试', '权威部门', '狮子座', '喜欢'], ['仅供参考', '位于', '为准', '平米', '相册', '地图搜索', '房产', '项目', '样板间', '开发商'], ['床底', '日益突出', '下恒大', '后装', '莱尔', '正在流行', '而亚盘', '保龄', '陈航', '个展'], ['记者', '警方', '一名', '随后', '发生', '发现', '接到', '来到', '现场', '时许'], ['市场', '经济', '投资', '下跌', '投资者', '大幅', '预期', '上涨', '资金', '显示'], ['玩家', '游戏', '体育讯', '精彩', '全新', '开启', '冠军', '网游', '比赛', '体验'], ['床底', '莱尔', '陈航', '下恒大', '办个', '回头路', '国球', '后装', '译言网', '曾子墨'], ['发展', '产品', '企业', '提供', '品牌', '中国', '消费者', '方式', '服务', '相关']]


In [61]:
from stream_topic.models import KmeansTM,BERTopicTM,CBC,DCTE,NMFTM,SOMTM,CEDC,ETM,LDA,ProdLDA,SOMTM,NSTM,WordCluTM,CTM,TNTM,NeuralLDA,CTMNeg
from stream_topic.utils import TMDataset
#本段落用时9min
dataset = TMDataset(language="chinese", stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt')# 
# dataset.fetch_dataset(name = "cnews_test", dataset_path = "/hongyi/stream/dataset", source = 'local')
dataset.fetch_dataset(name = "THUCNews", dataset_path = "/hongyi/stream/dataset/paper_data", source = 'local')
dataset.preprocess(model_type="KmeansTM", min_word_length = 1)

2025-03-14 15:39:35.696 | INFO     | stream_topic.utils.dataset:fetch_dataset:119 - Fetching dataset: THUCNews
2025-03-14 15:39:35.697 | INFO     | stream_topic.utils.dataset:fetch_dataset:129 - Fetching dataset from local path
Preprocessing documents: 100%|███████████████████████████████████████████████| 804736/804736 [3:37:51<00:00, 61.56it/s]


In [62]:
word_counts = dataset.dataframe['tokens'].apply(len)
stats = word_counts.describe() 
print("分词统计信息：")
print(stats)

分词统计信息：
count    804736.000000
mean        258.021808
std         187.174585
min           3.000000
25%         118.000000
50%         210.000000
75%         350.000000
max        1170.000000
Name: tokens, dtype: float64


In [63]:
all_words = [word for tokens in dataset.dataframe['tokens'] for word in tokens]
unique_words_total = len(set(all_words))
print("整个数据集的唯一词总数：", unique_words_total)

整个数据集的唯一词总数： 1004369


In [3]:
metric=cPMI(dataset=dataset)
metric.score(topics)

2.2260564970560743

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
# 加载 SentenceTransformer 模型
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(['球队','光学','橱柜','公司', '苹果'])
cosine_similarity(vec)

array([[0.99999994, 0.29257238, 0.41838545, 0.52985525, 0.44297022],
       [0.29257238, 0.9999996 , 0.4790189 , 0.3950327 , 0.38514268],
       [0.41838545, 0.4790189 , 1.0000002 , 0.54281676, 0.49406898],
       [0.52985525, 0.3950327 , 0.54281676, 1.0000005 , 0.5121894 ],
       [0.44297022, 0.38514268, 0.49406898, 0.5121894 , 1.        ]],
      dtype=float32)

In [2]:
import numpy as np
from scipy.spatial import distance
from sentence_transformers import SentenceTransformer

# 加载模型并编码
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(['普京', '乌克兰', '俄罗斯', '克里姆林宫', '北约', '苏联'])
similarity_matrix = np.zeros((6,  6))

for i in range(6):
    for j in range(6):
        dot_product = np.dot(vec[i],  vec[j])
        norm_i = np.linalg.norm(vec[i]) 
        norm_j = np.linalg.norm(vec[j]) 
        similarity = dot_product / (norm_i * norm_j)
        similarity_matrix[i][j] = similarity 

# 打印相似度矩阵 
print(similarity_matrix)


[[0.99999994 0.83445036 0.88558853 0.76523662 0.81512457 0.83173364]
 [0.83445036 1.         0.87225097 0.75497782 0.81245846 0.83140147]
 [0.88558853 0.87225097 1.         0.69245642 0.81220454 0.88812649]
 [0.76523662 0.75497782 0.69245642 1.         0.73059052 0.69534308]
 [0.81512457 0.81245846 0.81220454 0.73059052 1.         0.83622676]
 [0.83173364 0.83140147 0.88812649 0.69534308 0.83622676 1.        ]]


In [3]:
model = SentenceTransformer('/hongyi/stream/sentence-transformers/paraphrase-MiniLM-L3-v2')
vec = model.encode(['putin', 'ukraine', 'russia', 'kremlin', 'nato', 'soviet'])
similarity_matrix2 = np.zeros((6,  6))

for i in range(6):
    for j in range(6):
        dot_product = np.dot(vec[i],  vec[j])
        norm_i = np.linalg.norm(vec[i]) 
        norm_j = np.linalg.norm(vec[j]) 
        similarity = dot_product / (norm_i * norm_j)
        similarity_matrix2[i][j] = similarity 

# 打印相似度矩阵 
print(similarity_matrix2)

[[1.         0.39107469 0.57671314 0.34714741 0.23092447 0.50201404]
 [0.39107469 1.00000012 0.50474203 0.18075679 0.29826635 0.48116407]
 [0.57671314 0.50474203 0.99999994 0.30719069 0.16236597 0.66062617]
 [0.34714741 0.18075679 0.30719069 1.         0.18393187 0.26600564]
 [0.23092447 0.29826635 0.16236597 0.18393187 0.99999994 0.31564379]
 [0.50201404 0.48116407 0.66062617 0.26600564 0.31564379 1.00000012]]


In [6]:
# evaluate PMI
import pandas as pd
df = pd.DataFrame(similarity_matrix)
df2 = pd.DataFrame(similarity_matrix2)
upper_triangle_list_zh = [df.iloc[i, j] for i in range(6) for j in range(i+1, 6)]
upper_triangle_list_en = [df2.iloc[i, j] for i in range(6) for j in range(i+1, 6)]

# 对列表中的数据进行排序并获取排名
sorted_indices_zh = sorted(range(len(upper_triangle_list_zh)), key=lambda k: upper_triangle_list_zh[k])
ranks_zh = [sorted_indices_zh.index(i) + 1 for i in range(len(upper_triangle_list_zh))]
sorted_indices_en = sorted(range(len(upper_triangle_list_en)), key=lambda k: upper_triangle_list_en[k])
ranks_en = [sorted_indices_en.index(i) + 1 for i in range(len(upper_triangle_list_en))]

print(ranks_zh)
print(ranks_en)

sum = 0
for i in range(len(upper_triangle_list_zh)):
    sum += abs(ranks_zh[i]-ranks_en[i])
print(sum)

[11, 14, 5, 8, 10, 13, 4, 7, 9, 1, 6, 15, 3, 2, 12]
[10, 14, 9, 4, 12, 13, 2, 6, 11, 7, 1, 15, 3, 5, 8]
34


In [32]:
import numpy as np
score_list=[]
metric = ISIM(n_words=5)
metric.score_per_topic(topics)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/


{'比赛, 球队': 0.45917001366615295, '海洋, 海洋': 0.3639500141143799}

In [33]:
import numpy as np
score_list=[]
metric = ISIM(n_words=5)
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISIM scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISIM scores: 0.46434505715966223


In [2]:
from stream_topic.metrics import ISIM, INT, ISH,Expressivity, NPMI, Embedding_Coherence, Embedding_Topic_Diversity,cPMI
from sentence_transformers import SentenceTransformer
from stream_topic.metrics.metrics_config import MetricsConfig
MetricsConfig.set_PARAPHRASE_embedder("/hongyi/stream/sentence-transformers/Conan-embedding-v1/")#paraphrase-multilingual-mpnet-base-v2
MetricsConfig.set_SENTENCE_embedder("/hongyi/stream/sentence-transformers/Conan-embedding-v1/")#all-mpnet-base-v2

In [2]:
topics=[['全国人大外事委员会', '澳门特别行政区政府', '澳门特区政府', '中办国办', '国家体改委', '全国人大常委会法制工作委员会', '中央政法委员会', '国管局', '国情咨文', '中央对外联络部'], ['必玩网', '棋中局', '网侠会', '聚豪球会', '网戏', '网互娱', '网货会', '淘游网', '网战以', '抢战大场'], ['数码像机', '画面质量', '成像机', '数码相机', '先进设备', '电影摄影机', '数字相机', '成像仪', '成套设备', '投影设备'], ['湖人战', '湖人裁', '队上季', '湖人终', '湖人灭', '职棒大赛', '中甲球会', '湖人超', '湖人球权', '湖人秀'], ['高考作文', '高考题', '高考状元', '研考会', '高考制度', '社考', '中考题', '考评组', '评课', '期中考'], ['美衣', '美服', '时尚女装', '艳服', '时装戏', '连衣裙', '时装周', '春装展示', '美和带', '裙百搭'], ['证券行情', '沪深股市', '证券业', '基金业', '证券界', '投资业', '港股', '财经证券', '中盘股', '期股'], ['情色电影', '谍战大剧', '大热美剧', '电影明星', '青年电影制片厂', '季播剧', '剧独播剧', '电影界', '电影站', '剧选角'], ['房产局', '房产网', '房环市', '安居工程', '别墅网', '房协建', '选房区', '房产频道', '游览区', '地市馆'], ['央企辅业', '产业布局', '房产业', '央企频', '商建刚', '央企增', '安居工程', '特色产业', '中交建料', '房协建']]

In [3]:
import numpy as np
score_list=[]
metric = ISIM()
metric.score_per_topic(topics)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/


{'全国人大外事委员会, 澳门特别行政区政府, 澳门特区政府, 中办国办, 国家体改委': 0.6597099900245667,
 '必玩网, 棋中局, 网侠会, 聚豪球会, 网戏': 0.6234099864959717,
 '数码像机, 画面质量, 成像机, 数码相机, 先进设备': 0.5014500021934509,
 '湖人战, 湖人裁, 队上季, 湖人终, 湖人灭': 0.4491100013256073,
 '高考作文, 高考题, 高考状元, 研考会, 高考制度': 0.6532899737358093,
 '美衣, 美服, 时尚女装, 艳服, 时装戏': 0.510640025138855,
 '证券行情, 沪深股市, 证券业, 基金业, 证券界': 0.5092999935150146,
 '情色电影, 谍战大剧, 大热美剧, 电影明星, 青年电影制片厂': 0.5776900053024292,
 '房产局, 房产网, 房环市, 安居工程, 别墅网': 0.5921599864959717,
 '央企辅业, 产业布局, 房产业, 央企频, 商建刚': 0.607230007648468}

In [16]:
import numpy as np
score_list=[]
metric = ISIM()
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISIM scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISIM scores: 0.605107569605112


In [4]:
score_list=[]
metric = INT()
for i in range(100):    
    scores = metric.score(topics) #值越大越好
    score_list.append(scores)
print("INT scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
INT scores: 0.09399999999999999


In [5]:
score_list=[]
metric = ISH()
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISH scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISH scores: 0.876039650440216


In [2]:
import pandas as pd
def load_stopwords(stopwords_path):
        # load Chinese stopwords list
        return pd.read_csv(stopwords_path, names=['w'], sep='\t', encoding='UTF-8')
stopword = load_stopwords('/hongyi/stream/stopwords/baidu_stopwords.txt')

In [8]:
import numpy as np
# topics = [["apple", "banana", "cherry", "date", "fig","apple", "banana", "cherry", "date", "fig","apple", "banana", "cherry", "date", "fig"],
#           ["dog", "cat", "rabbit", "hamster", "gerbil","dog", "cat", "rabbit", "hamster", "gerbil","dog", "cat", "rabbit", "hamster", "gerbil"]]
expressivity_metric = Expressivity(
n_words=10,
custom_stopwords=list(stopword['w'])
)
beta = np.random.rand(2, 10)
info = expressivity_metric.get_info()
print("Metric Info:", info)
for i in range(100):    
    scores = expressivity_metric.score(topics, beta) #值越小越好
    score_list.append(scores)
print("Expressivity scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Metric Info: {'metric_name': 'Expressivity', 'n_words': 10, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 1024, 'out_features': 1792, 'bias': True, 'activation_function': 'torch.nn.modules.linear.Identity'})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The expressivity metric measures the distance between the mean vector of the top words in a topic and the mean vector of the embeddings of the stop words.'}
Expressivity scores: 0.825089825220108


In [9]:
beta = np.random.rand(2, 384)
diversity_metric = Embedding_Topic_Diversity()
info = diversity_metric.get_info()
print("Metric Info:", info)
for i in range(100):    
    scores = diversity_metric.score(topics, beta)  #值越小越好
    score_list.append(scores)
print("Diversity score:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Metric Info: {'metric_name': 'Embedding Topic Diversity', 'n_words': 10, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 1024, 'out_features': 1792, 'bias': True, 'activation_function': 'torch.nn.modules.linear.Identity'})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The diversity metric measures the mean cosine similarity of the mean vectors of the top words of all topics.'}
Diversity score: 0.8772571452130032


In [4]:
from stream_topic.utils import TMDataset
#本段落用时9min
dataset = TMDataset(language="chinese", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt')# 
dataset.fetch_dataset(name = "THUCNews_corpus", dataset_path = "/hongyi/stream/dataset/processed_dataset", source = 'local')
dataset.preprocess(model_type="KmeansTM")#, min_word_length = 1

2025-01-15 16:59:42.864 | INFO     | stream_topic.utils.dataset:fetch_dataset:120 - Fetching dataset: THUCNews_corpus
2025-01-15 16:59:42.864 | INFO     | stream_topic.utils.dataset:fetch_dataset:130 - Fetching dataset from local path
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.945 seconds.
Prefix dict has been built successfully.


KeyboardInterrupt: 

In [30]:
topics=[['game', 'people', 'said', 'service', 'also', 'user', 'player', 'time', 'video', 'one'], ['said', 'site', 'would', 'people', 'film', 'system', 'first', 'could', 'dvd', 'also'], ['said', 'year', 'email', 'game', 'would', 'computer', 'virus', 'people', 'one', 'company'], ['said', 'people', 'would', 'game', 'new', 'one', 'could', 'also', 'time', 'market'], ['said', 'technology', 'people', 'phone', 'mobile', 'year', 'new', 'music', 'one', 'firm']]

In [33]:
metric = NPMI(dataset,language = "chinese", custom_stopwords=list(stopword)) #值越大越好  
scores = metric.score([['比赛', '球队']])  #值越大越好
print("NPMI score:", scores)

NPMI score: 0.72734


In [41]:
metric = Embedding_Coherence()
topic_scores = metric.score_per_topic(topics)
print("Coherence scores per topic:", topic_scores)
overall_score = metric.score(topics)
print("Overall coherence score:", overall_score)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Coherence scores per topic: {'比赛, 球队': 0.76253, '海洋, 海洋': 1.0}
Overall coherence score: 0.881265


In [11]:
topics = ["香蕉","公司","科技","谷歌"]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
# 加载 SentenceTransformer 模型
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(topics)
cosine_similarity(vec)

array([[1.0000001 , 0.45954525, 0.3126009 , 0.56101286],
       [0.45954525, 1.0000006 , 0.4346076 , 0.54723996],
       [0.3126009 , 0.4346076 , 0.9999999 , 0.63667595],
       [0.56101286, 0.54723996, 0.63667595, 0.99999994]], dtype=float32)