In [1]:
topics = [['比赛', '体育讯', '球队', '防守', '季后赛', '球员', '进攻', '篮板', '热火', '湖人'],['比赛', '球队', '热火', '球员', '季后赛', '防守', '湖人', '篮板', '科比', '凯尔特人']]

In [32]:
import pandas as pd

# 读取文件并加载为 DataFrame
df = pd.read_csv('/hongyi/stream/dataset/chinese_thucnews_cedc_cleaned.txt', sep='\t', header=None, names=['text','labels'])

# 查看结果
print(df.head())


                                                text labels
0  胜负彩11066期部分专业媒体复式推荐总汇   说明：媒体推荐的“历史命中率统计”表示媒体历...     彩票
1  胜负彩11097期部分专业媒体复式推荐总汇 说明：媒体推荐的“历史命中率统计”表示媒体历史平...     彩票
2  胜负彩第09069期国内部分专业媒体复式推荐总汇表 说明：媒体推荐的“历史命中率统计”表示媒...     彩票
3  单期361注2等奖改写历史 全偶号让双色球头奖走低 　　双色球第09083期头奖爆出11注5...     彩票
4  双色球头奖14注597万 二等124注16万奖池1.33亿 　　新浪体育讯　北京时间2011...     彩票


In [25]:
with open('/hongyi/stream/dataset/chinese_thucnews_cedc.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

cleaned_lines = []
for line in lines:
    # 确保每行只有两个字段（标签和文本），如果多余的字段被分割，可以将其合并
    fields = line.split('\t')
    if len(fields) == 2:
        cleaned_lines.append(line)  # 正常的行保留
    elif len(fields) > 2:
        # 合并多余的字段
        cleaned_lines.append(f"{fields[0]}\t{' '.join(fields[1:]).strip()}\n")

# 保存清洗后的数据
with open('/hongyi/stream/dataset/chinese_thucnews_cedc_cleaned.txt', 'w', encoding='utf-8') as f:
    f.writelines(cleaned_lines)

print("清洗后的文件保存为 'chinese_thucnews_cedc_cleaned.txt'。")


清洗后的文件保存为 'chinese_thucnews_cedc_cleaned.txt'。


In [33]:
#本段落用时9min
from stream_topic.utils.dataset import TMDataset

# 创建 TMDataset 实例
dataset = TMDataset()#language="zh-cn", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt'

# 假设你有一个名为 df 的 DataFrame，包含你的数据
# df = pd.DataFrame(...)

# 数据集名称
dataset_name = "THUs"

# 指定保存数据集的目录
save_dir = "/hongyi/stream/dataset"
# df = df.iloc[0:100]
# 调用 create_load_save_dataset 方法来存储数据集
dataset.create_load_save_dataset(
    data=df,
    dataset_name=dataset_name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    save_dir=save_dir,
    doc_column="text",  # 假设 DataFrame 中包含文本的列名为 "text_column"
    label_column="labels",  # 假设 DataFrame 中包含标签的列名为 "label_column"
    language = "chinese",
    stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt',
    min_word_length = 1
)

# 打印保存的数据集信息
print(dataset.dataframe.head())

Preprocessing documents: 100%|███████████████████████████████████████████████████| 836075/836075 [2:50:25<00:00, 81.77it/s]
2025-01-16 12:29:57.095 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:239 - Dataset saved to /hongyi/stream/dataset/THUs.parquet
2025-01-16 12:29:57.970 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:254 - Dataset info saved to /hongyi/stream/dataset/THUs_info.pkl


  language                                stopwords_path  min_word_length  \
0  chinese  /hongyi/stream/stopwords/baidu_stopwords.txt                1   
1  chinese  /hongyi/stream/stopwords/baidu_stopwords.txt                1   
2  chinese  /hongyi/stream/stopwords/baidu_stopwords.txt                1   
3  chinese  /hongyi/stream/stopwords/baidu_stopwords.txt                1   
4  chinese  /hongyi/stream/stopwords/baidu_stopwords.txt                1   

                                                text labels  
0  胜负彩 期 媒体 推荐 媒体 推荐 历史 统计 媒体 历史 命中 历史 命中 胜负彩 胜负彩...     彩票  
1  胜负彩 期 专业 媒体 复式 推荐 总汇 媒体 推荐 历史 命中率 统计 媒体 历史 平均 ...     彩票  
2  胜负彩 期 专业 媒体 复式 推荐 总汇 媒体 推荐 历史 命中率 统计 媒体 历史 平均 ...     彩票  
3   注 历史 双色球 头奖 双色球 期 头奖 爆出 注 万 二等奖 井喷 注 万 揽 注 揽 ...     彩票  
4  双色球 头奖 注 万 二等 注 亿 新浪 北京 年 双色球 期 开出 奖 号 红球 蓝球 注...     彩票  


In [38]:
topics = [['球队','光学','橱柜','听力','房价'],['海洋','海洋','海洋','海洋','海洋']]

In [40]:
topics = [['比赛', '球队', '热火', '球员', '季后赛'],['海洋','海洋','海洋','海洋','海洋']]

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
# 加载 SentenceTransformer 模型
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(['球队','光学','橱柜','公司', '苹果'])
cosine_similarity(vec)

array([[0.99999994, 0.29257238, 0.41838545, 0.52985525, 0.44297022],
       [0.29257238, 0.9999996 , 0.4790189 , 0.3950327 , 0.38514268],
       [0.41838545, 0.4790189 , 1.0000002 , 0.54281676, 0.49406898],
       [0.52985525, 0.3950327 , 0.54281676, 1.0000005 , 0.5121894 ],
       [0.44297022, 0.38514268, 0.49406898, 0.5121894 , 1.        ]],
      dtype=float32)

In [20]:
import numpy as np
from scipy.spatial import distance
from sentence_transformers import SentenceTransformer

# 加载模型并编码
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(['球队', '光学', '橱柜', '公司', '苹果'])

# 计算欧氏距离矩阵
euclidean_dist_matrix = distance.cdist(vec, vec, 'euclidean')
print("欧氏距离矩阵:")
print(euclidean_dist_matrix)

# 计算曼哈顿距离矩阵
manhattan_dist_matrix = distance.cdist(vec, vec, 'cityblock')
print("曼哈顿距离矩阵:")
print(manhattan_dist_matrix)

欧氏距离矩阵:
[[ 0.         27.15742488 25.38257414 23.20721193 24.92156337]
 [27.15742488  0.         23.05978956 25.32216344 25.13720352]
 [25.38257414 23.05978956  0.         22.66768397 23.51168853]
 [23.20721193 25.32216344 22.66768397  0.         23.48759552]
 [24.92156337 25.13720352 23.51168853 23.48759552  0.        ]]
曼哈顿距离矩阵:
[[  0.         910.771954   853.17430964 783.16835684 844.351835  ]
 [910.771954     0.         773.64924929 840.24629857 836.29914488]
 [853.17430964 773.64924929   0.         761.6664871  788.13965886]
 [783.16835684 840.24629857 761.6664871    0.         794.87273323]
 [844.351835   836.29914488 788.13965886 794.87273323   0.        ]]


In [32]:
import numpy as np
score_list=[]
metric = ISIM(n_words=5)
metric.score_per_topic(topics)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/


{'比赛, 球队': 0.45917001366615295, '海洋, 海洋': 0.3639500141143799}

In [33]:
import numpy as np
score_list=[]
metric = ISIM(n_words=5)
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISIM scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISIM scores: 0.46434505715966223


In [1]:
from stream_topic.metrics import ISIM, INT, ISH,Expressivity, NPMI, Embedding_Coherence, Embedding_Topic_Diversity
from sentence_transformers import SentenceTransformer
from stream_topic.metrics.metrics_config import MetricsConfig
MetricsConfig.set_PARAPHRASE_embedder("/hongyi/stream/sentence-transformers/Conan-embedding-v1/")#paraphrase-multilingual-mpnet-base-v2
MetricsConfig.set_SENTENCE_embedder("/hongyi/stream/sentence-transformers/Conan-embedding-v1/")#all-mpnet-base-v2

/hongyi/anaconda3/envs/mystream/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [2]:
topics=[['全国人大外事委员会', '澳门特别行政区政府', '澳门特区政府', '中办国办', '国家体改委', '全国人大常委会法制工作委员会', '中央政法委员会', '国管局', '国情咨文', '中央对外联络部'], ['必玩网', '棋中局', '网侠会', '聚豪球会', '网戏', '网互娱', '网货会', '淘游网', '网战以', '抢战大场'], ['数码像机', '画面质量', '成像机', '数码相机', '先进设备', '电影摄影机', '数字相机', '成像仪', '成套设备', '投影设备'], ['湖人战', '湖人裁', '队上季', '湖人终', '湖人灭', '职棒大赛', '中甲球会', '湖人超', '湖人球权', '湖人秀'], ['高考作文', '高考题', '高考状元', '研考会', '高考制度', '社考', '中考题', '考评组', '评课', '期中考'], ['美衣', '美服', '时尚女装', '艳服', '时装戏', '连衣裙', '时装周', '春装展示', '美和带', '裙百搭'], ['证券行情', '沪深股市', '证券业', '基金业', '证券界', '投资业', '港股', '财经证券', '中盘股', '期股'], ['情色电影', '谍战大剧', '大热美剧', '电影明星', '青年电影制片厂', '季播剧', '剧独播剧', '电影界', '电影站', '剧选角'], ['房产局', '房产网', '房环市', '安居工程', '别墅网', '房协建', '选房区', '房产频道', '游览区', '地市馆'], ['央企辅业', '产业布局', '房产业', '央企频', '商建刚', '央企增', '安居工程', '特色产业', '中交建料', '房协建']]

In [3]:
import numpy as np
score_list=[]
metric = ISIM()
metric.score_per_topic(topics)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/


{'全国人大外事委员会, 澳门特别行政区政府, 澳门特区政府, 中办国办, 国家体改委': 0.6597099900245667,
 '必玩网, 棋中局, 网侠会, 聚豪球会, 网戏': 0.6234099864959717,
 '数码像机, 画面质量, 成像机, 数码相机, 先进设备': 0.5014500021934509,
 '湖人战, 湖人裁, 队上季, 湖人终, 湖人灭': 0.4491100013256073,
 '高考作文, 高考题, 高考状元, 研考会, 高考制度': 0.6532899737358093,
 '美衣, 美服, 时尚女装, 艳服, 时装戏': 0.510640025138855,
 '证券行情, 沪深股市, 证券业, 基金业, 证券界': 0.5092999935150146,
 '情色电影, 谍战大剧, 大热美剧, 电影明星, 青年电影制片厂': 0.5776900053024292,
 '房产局, 房产网, 房环市, 安居工程, 别墅网': 0.5921599864959717,
 '央企辅业, 产业布局, 房产业, 央企频, 商建刚': 0.607230007648468}

In [16]:
import numpy as np
score_list=[]
metric = ISIM()
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISIM scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISIM scores: 0.605107569605112


In [4]:
score_list=[]
metric = INT()
for i in range(100):    
    scores = metric.score(topics) #值越大越好
    score_list.append(scores)
print("INT scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
INT scores: 0.09399999999999999


In [5]:
score_list=[]
metric = ISH()
for i in range(100):    
    scores = metric.score(topics) #值越小越好
    score_list.append(scores)
print("ISH scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
ISH scores: 0.876039650440216


In [2]:
import pandas as pd
def load_stopwords(stopwords_path):
        # load Chinese stopwords list
        return pd.read_csv(stopwords_path, names=['w'], sep='\t', encoding='UTF-8')
stopword = load_stopwords('/hongyi/stream/stopwords/baidu_stopwords.txt')

In [8]:
import numpy as np
# topics = [["apple", "banana", "cherry", "date", "fig","apple", "banana", "cherry", "date", "fig","apple", "banana", "cherry", "date", "fig"],
#           ["dog", "cat", "rabbit", "hamster", "gerbil","dog", "cat", "rabbit", "hamster", "gerbil","dog", "cat", "rabbit", "hamster", "gerbil"]]
expressivity_metric = Expressivity(
n_words=10,
custom_stopwords=list(stopword['w'])
)
beta = np.random.rand(2, 10)
info = expressivity_metric.get_info()
print("Metric Info:", info)
for i in range(100):    
    scores = expressivity_metric.score(topics, beta) #值越小越好
    score_list.append(scores)
print("Expressivity scores:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Metric Info: {'metric_name': 'Expressivity', 'n_words': 10, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 1024, 'out_features': 1792, 'bias': True, 'activation_function': 'torch.nn.modules.linear.Identity'})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The expressivity metric measures the distance between the mean vector of the top words in a topic and the mean vector of the embeddings of the stop words.'}
Expressivity scores: 0.825089825220108


In [9]:
beta = np.random.rand(2, 384)
diversity_metric = Embedding_Topic_Diversity()
info = diversity_metric.get_info()
print("Metric Info:", info)
for i in range(100):    
    scores = diversity_metric.score(topics, beta)  #值越小越好
    score_list.append(scores)
print("Diversity score:", np.mean(score_list))

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Metric Info: {'metric_name': 'Embedding Topic Diversity', 'n_words': 10, 'embedding_model_name': SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 1024, 'out_features': 1792, 'bias': True, 'activation_function': 'torch.nn.modules.linear.Identity'})
), 'metric_range': '0 to 1, smaller is better', 'description': 'The diversity metric measures the mean cosine similarity of the mean vectors of the top words of all topics.'}
Diversity score: 0.8772571452130032


In [4]:
from stream_topic.utils import TMDataset
#本段落用时9min
dataset = TMDataset(language="chinese", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt')# 
dataset.fetch_dataset(name = "THUCNews_corpus", dataset_path = "/hongyi/stream/dataset/processed_dataset", source = 'local')
dataset.preprocess(model_type="KmeansTM")#, min_word_length = 1

2025-01-15 16:59:42.864 | INFO     | stream_topic.utils.dataset:fetch_dataset:120 - Fetching dataset: THUCNews_corpus
2025-01-15 16:59:42.864 | INFO     | stream_topic.utils.dataset:fetch_dataset:130 - Fetching dataset from local path
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.945 seconds.
Prefix dict has been built successfully.


KeyboardInterrupt: 

In [30]:
topics=[['game', 'people', 'said', 'service', 'also', 'user', 'player', 'time', 'video', 'one'], ['said', 'site', 'would', 'people', 'film', 'system', 'first', 'could', 'dvd', 'also'], ['said', 'year', 'email', 'game', 'would', 'computer', 'virus', 'people', 'one', 'company'], ['said', 'people', 'would', 'game', 'new', 'one', 'could', 'also', 'time', 'market'], ['said', 'technology', 'people', 'phone', 'mobile', 'year', 'new', 'music', 'one', 'firm']]

In [33]:
metric = NPMI(dataset,language = "chinese", custom_stopwords=list(stopword)) #值越大越好  
scores = metric.score([['比赛', '球队']])  #值越大越好
print("NPMI score:", scores)

NPMI score: 0.72734


In [41]:
metric = Embedding_Coherence()
topic_scores = metric.score_per_topic(topics)
print("Coherence scores per topic:", topic_scores)
overall_score = metric.score(topics)
print("Overall coherence score:", overall_score)

Loading model from local path: /hongyi/stream/sentence-transformers/Conan-embedding-v1/
Coherence scores per topic: {'比赛, 球队': 0.76253, '海洋, 海洋': 1.0}
Overall coherence score: 0.881265


In [11]:
topics = ["香蕉","公司","科技","谷歌"]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
# 加载 SentenceTransformer 模型
model = SentenceTransformer('/hongyi/stream/sentence-transformers/Conan-embedding-v1')
vec = model.encode(topics)
cosine_similarity(vec)

array([[1.0000001 , 0.45954525, 0.3126009 , 0.56101286],
       [0.45954525, 1.0000006 , 0.4346076 , 0.54723996],
       [0.3126009 , 0.4346076 , 0.9999999 , 0.63667595],
       [0.56101286, 0.54723996, 0.63667595, 0.99999994]], dtype=float32)